name: segment
description: "Fluter segment User interface"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  provider: ^6.1.2
  http: ^1.2.1
  fl_chart: ^0.68.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_icons:
  android: true
  windows: true
  ios: true
  image_path: "assets/images/Icon.png"
